Server: Server.cpp
	g++ -o Server Server.cpp

Client:Client.cpp
	g++ -o Client Client.cpp

clean:
	rm Client Server ClientBasicBook ServerBasicBook

ServerBasicBook: ServerBasicBook.cpp NetworkApplication.cpp
	g++ -o ServerBasicBook ServerBasicBook.cpp NetworkApplication.cpp

ClientBasicBook: ClientBasicBook.cpp NetworkApplication.cpp
	g++ -o ClientBasicBook ClientBasicBook.cpp NetworkApplication.cpp